export interface ISF {
    seqNo : Number,
    refNo: number,
    fileNo: String,
    branch : String,
    isfNo : String,
    status : String,
    disposition: String,
    type: any,
    shipmentType: String,
    actReason : String,
    importerCode : String,
    ImpIdtype : String,
    importerName : String,
    bondHolderId : String,
    bondActCode: String,
    bondtype: String,
    houseBL : String,
    regularBL: Number,
    masterBL: String,
    oiRefNo : String,
    updatedDate: String,
    user: String,
    invDate: String,
}
