runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: dist/angular-admin-first/index.html
  upload: dist/angular-admin-first/index.html

- url: /
  static_dir: dist/angular-admin-first

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.md$
  - ^LICENSE
